# This file is generated by Makefile, please do not modify it directly.
PO :=
HTMLDIROPENRC_fr := html-fr-openrc
HTMLDIRSYSD_fr := html-fr-systemd
HTMLTAROPENRC_fr := LFS-OPENRC-BOOK-$(MILESTONE)-fr-HTML.tar.bz2
HTMLTARSYSD_fr := LFS-SYSD-BOOK-$(MILESTONE)-fr-HTML.tar.bz2
PDFOPENRC_fr := LFS-OPENRC-BOOK-$(MILESTONE)-fr.pdf
PDFSYSD_fr := LFS-SYSD-BOOK-$(MILESTONE)-fr.pdf
EPUBOPENRC_fr := LFS-OPENRC-BOOK-$(MILESTONE)-fr.epub
EPUBSYSD_fr := LFS-SYSD-BOOK-$(MILESTONE)-fr.epub

XML_fr := $(shell find $(ORIGDIR) -name '*.xml' -o -name '*stylesheets*' -prune -a -type f | sed "s|$(ORIGDIR)/|lfsgen-fr/|g" | tr '\n' ' ')
PO_fr := $(shell find $(ORIGDIR) -name '*.xml' -o -name '*stylesheets*' -prune -a -type f | sed "s|$(ORIGDIR)/|fr/|g" | sed 's|.xml$$|.po|' | tr '\n' ' ')
PO += $(PO_fr)
IMAGES_fr := $(shell find images -type f | sed "s|^|lfsgen-fr/|g" | tr '\n' ' ')
STYLESHEETS_fr := $(shell find stylesheets -type f | sed "s|^|lfsgen-fr/|g" | tr '\n' ' ')
COPY_fr := $(addprefix lfsgen-fr/,$(filestoget))

lfsgen-fr/images/%: images/%
	mkdir -p $$(dirname $@)
	@rm -f $@
	cp $< $@

lfsgen-fr/stylesheets/%: stylesheets/%
	mkdir -p $$(dirname $@)
	@rm -f $@
	cp $< $@

lfsgen-fr/%.xml: $(ORIGDIR)/%.xml fr/%.po sed-fr
	mkdir -p $$(dirname $@)
	LANG=$(LANG_fr) po4a-translate -k 0 -f docbook -m $< -l $@.tmp -p $(word 2,$^)
	./$(word 3,$^) $@
	rm $@.tmp

fr/%.po: $(ORIGDIR)/%.xml
	mkdir -p $$(dirname $@)
	LANG=$(LANG_fr) po4a-updatepo -f docbook -m $< -p $@
	python3 set-xml.py $@
	@touch $@

clean-gen-fr:
	rm -rf lfsgen-fr

clean-product-fr:
	rm -rf $(HTMLTAROPENRC_fr)
	rm -rf $(HTMLTARSYSD_fr)
	rm -rf $(HTMLDIROPENRC_fr)
	rm -rf $(HTMLDIRSYSD_fr)
	rm -rf $(PDFOPENRC_fr)
	rm -rf $(PDFSYSD_fr)
	rm -rf $(EPUBOPENRC_fr)
	rm -rf $(EPUBSYSD_fr)

.SECONDEXPANSION:
$(addprefix lfsgen-fr/,$(filestocopy)): INPUT=$(ORIGDIR)$(subst lfsgen-fr,,$@)
$(addprefix lfsgen-fr/,$(filestocopy)): $$(INPUT)
	mkdir -p $$(dirname $@)
	if [ -f $< ]; then cp $< $@; else cp -r $< $$(dirname $@); fi

genhtml-fr-openrc: $(XML_fr) $(COPY_fr) $(IMAGES_fr) $(STYLESHEETS_fr)
	LANG=$(LANG_fr) make -C lfsgen-fr -j1 REV=openrc BASEDIR=../$(HTMLDIROPENRC_fr) book

genhtml-fr-sysd: $(XML_fr) $(COPY_fr) $(IMAGES_fr) $(STYLESHEETS_fr)
	LANG=$(LANG_fr) make -C lfsgen-fr -j1 REV=systemd BASEDIR=../$(HTMLDIRSYSD_fr) book

genpdf-fr-openrc: $(PDFOPENRC_fr)

$(PDFOPENRC_fr): $(XML_fr) $(COPY_fr) $(IMAGES_fr) $(STYLESHEETS_fr)
	LANG=$(LANG_fr) make -C lfsgen-fr -j1 REV=openrc BASEDIR=.. pdf
	mv LFS-OPENRC.pdf $@

genpdf-fr-sysd: $(PDFSYSD_fr)

$(PDFSYSD_fr): $(XML_fr) $(COPY_fr) $(IMAGES_fr) $(STYLESHEETS_fr)
	LANG=$(LANG_fr) make -C lfsgen-fr -j1 REV=systemd BASEDIR=.. pdf
	mv LFS-SYSD-BOOK.pdf $@

gentar-fr-openrc: $(HTMLTAROPENRC_fr)
$(HTMLTAROPENRC_fr): $(XML_fr) $(COPY_fr) $(IMAGES_fr) $(STYLESHEETS_fr) genhtml-fr-openrc
	rm -f $@
	tar cjf $@ $(HTMLDIROPENRC_fr)

gentar-fr-sysd: $(HTMLTARSYSD_fr)
$(HTMLTARSYSD_fr): $(XML_fr) $(COPY_fr) $(IMAGES_fr) $(STYLESHEETS_fr) genhtml-fr-sysd
	rm -f $@
	tar cjf $@ $(HTMLDIRSYSD_fr)

genepub-fr-openrc: $(EPUBOPENRC_fr)
$(EPUBOPENRC_fr): $(XML_fr) $(COPY_fr) $(IMAGES_fr) $(STYLESHEETS_fr)
	LANG=$(LANG_fr) make -C lfsgen-fr -j1 REV=openrc EPUB_OUTPUT=$@ epub

genepub-fr-sysd: $(EPUBSYSD_fr)
$(EPUBSYSD_fr): $(XML_fr) $(COPY_fr) $(IMAGES_fr) $(STYLESHEETS_fr)
	LANG=$(LANG_fr) make -C lfsgen-fr -j1 REV=systemd EPUB_OUTPUT=$@ epub

upload-fr-openrc: $(SSH_AGENT)
	cd $(HTMLDIROPENRC_fr) ;\
	chmod g+w -R . ;\
	rsync --progress --recursive * $(USER)@www.linuxfromscratch.org:/srv/www/www.fr.linuxfromscratch.org/view/lfs-svn/

upload-fr-sysd: $(SSH_AGENT)
	cd $(HTMLDIRSYSD_fr) ;\
	chmod g+w -R . ;\
	rsync --progress --recursive * $(USER)@www.linuxfromscratch.org:/srv/www/www.fr.linuxfromscratch.org/view/lfs-systemd-svn/
HTMLDIROPENRC_pt_BR := html-pt_BR-openrc
HTMLDIRSYSD_pt_BR := html-pt_BR-systemd
HTMLTAROPENRC_pt_BR := LFS-OPENRC-BOOK-$(MILESTONE)-pt_BR-HTML.tar.bz2
HTMLTARSYSD_pt_BR := LFS-SYSD-BOOK-$(MILESTONE)-pt_BR-HTML.tar.bz2
PDFOPENRC_pt_BR := LFS-OPENRC-BOOK-$(MILESTONE)-pt_BR.pdf
PDFSYSD_pt_BR := LFS-SYSD-BOOK-$(MILESTONE)-pt_BR.pdf
EPUBOPENRC_pt_BR := LFS-OPENRC-BOOK-$(MILESTONE)-pt_BR.epub
EPUBSYSD_pt_BR := LFS-SYSD-BOOK-$(MILESTONE)-pt_BR.epub

XML_pt_BR := $(shell find $(ORIGDIR) -name '*.xml' -o -name '*stylesheets*' -prune -a -type f | sed "s|$(ORIGDIR)/|lfsgen-pt_BR/|g" | tr '\n' ' ')
PO_pt_BR := $(shell find $(ORIGDIR) -name '*.xml' -o -name '*stylesheets*' -prune -a -type f | sed "s|$(ORIGDIR)/|pt_BR/|g" | sed 's|.xml$$|.po|' | tr '\n' ' ')
PO += $(PO_pt_BR)
IMAGES_pt_BR := $(shell find images -type f | sed "s|^|lfsgen-pt_BR/|g" | tr '\n' ' ')
STYLESHEETS_pt_BR := $(shell find stylesheets -type f | sed "s|^|lfsgen-pt_BR/|g" | tr '\n' ' ')
COPY_pt_BR := $(addprefix lfsgen-pt_BR/,$(filestoget))

lfsgen-pt_BR/images/%: images/%
	mkdir -p $$(dirname $@)
	@rm -f $@
	cp $< $@

lfsgen-pt_BR/stylesheets/%: stylesheets/%
	mkdir -p $$(dirname $@)
	@rm -f $@
	cp $< $@

lfsgen-pt_BR/%.xml: $(ORIGDIR)/%.xml pt_BR/%.po sed-pt_BR
	mkdir -p $$(dirname $@)
	LANG=$(LANG_pt_BR) po4a-translate -k 0 -f docbook -m $< -l $@.tmp -p $(word 2,$^)
	./$(word 3,$^) $@
	rm $@.tmp

pt_BR/%.po: $(ORIGDIR)/%.xml
	mkdir -p $$(dirname $@)
	LANG=$(LANG_pt_BR) po4a-updatepo -f docbook -m $< -p $@
	python3 set-xml.py $@
	@touch $@

clean-gen-pt_BR:
	rm -rf lfsgen-pt_BR

clean-product-pt_BR:
	rm -rf $(HTMLTAROPENRC_pt_BR)
	rm -rf $(HTMLTARSYSD_pt_BR)
	rm -rf $(HTMLDIROPENRC_pt_BR)
	rm -rf $(HTMLDIRSYSD_pt_BR)
	rm -rf $(PDFOPENRC_pt_BR)
	rm -rf $(PDFSYSD_pt_BR)
	rm -rf $(EPUBOPENRC_pt_BR)
	rm -rf $(EPUBSYSD_pt_BR)

.SECONDEXPANSION:
$(addprefix lfsgen-pt_BR/,$(filestocopy)): INPUT=$(ORIGDIR)$(subst lfsgen-pt_BR,,$@)
$(addprefix lfsgen-pt_BR/,$(filestocopy)): $$(INPUT)
	mkdir -p $$(dirname $@)
	if [ -f $< ]; then cp $< $@; else cp -r $< $$(dirname $@); fi

genhtml-pt_BR-openrc: $(XML_pt_BR) $(COPY_pt_BR) $(IMAGES_pt_BR) $(STYLESHEETS_pt_BR)
	LANG=$(LANG_pt_BR) make -C lfsgen-pt_BR -j1 REV=openrc BASEDIR=../$(HTMLDIROPENRC_pt_BR) book

genhtml-pt_BR-sysd: $(XML_pt_BR) $(COPY_pt_BR) $(IMAGES_pt_BR) $(STYLESHEETS_pt_BR)
	LANG=$(LANG_pt_BR) make -C lfsgen-pt_BR -j1 REV=systemd BASEDIR=../$(HTMLDIRSYSD_pt_BR) book

genpdf-pt_BR-openrc: $(PDFOPENRC_pt_BR)

$(PDFOPENRC_pt_BR): $(XML_pt_BR) $(COPY_pt_BR) $(IMAGES_pt_BR) $(STYLESHEETS_pt_BR)
	LANG=$(LANG_pt_BR) make -C lfsgen-pt_BR -j1 REV=openrc BASEDIR=.. pdf
	mv LFS-OPENRC.pdf $@

genpdf-pt_BR-sysd: $(PDFSYSD_pt_BR)

$(PDFSYSD_pt_BR): $(XML_pt_BR) $(COPY_pt_BR) $(IMAGES_pt_BR) $(STYLESHEETS_pt_BR)
	LANG=$(LANG_pt_BR) make -C lfsgen-pt_BR -j1 REV=systemd BASEDIR=.. pdf
	mv LFS-SYSD-BOOK.pdf $@

gentar-pt_BR-openrc: $(HTMLTAROPENRC_pt_BR)
$(HTMLTAROPENRC_pt_BR): $(XML_pt_BR) $(COPY_pt_BR) $(IMAGES_pt_BR) $(STYLESHEETS_pt_BR) genhtml-pt_BR-openrc
	rm -f $@
	tar cjf $@ $(HTMLDIROPENRC_pt_BR)

gentar-pt_BR-sysd: $(HTMLTARSYSD_pt_BR)
$(HTMLTARSYSD_pt_BR): $(XML_pt_BR) $(COPY_pt_BR) $(IMAGES_pt_BR) $(STYLESHEETS_pt_BR) genhtml-pt_BR-sysd
	rm -f $@
	tar cjf $@ $(HTMLDIRSYSD_pt_BR)

genepub-pt_BR-openrc: $(EPUBOPENRC_pt_BR)
$(EPUBOPENRC_pt_BR): $(XML_pt_BR) $(COPY_pt_BR) $(IMAGES_pt_BR) $(STYLESHEETS_pt_BR)
	LANG=$(LANG_pt_BR) make -C lfsgen-pt_BR -j1 REV=openrc EPUB_OUTPUT=$@ epub

genepub-pt_BR-sysd: $(EPUBSYSD_pt_BR)
$(EPUBSYSD_pt_BR): $(XML_pt_BR) $(COPY_pt_BR) $(IMAGES_pt_BR) $(STYLESHEETS_pt_BR)
	LANG=$(LANG_pt_BR) make -C lfsgen-pt_BR -j1 REV=systemd EPUB_OUTPUT=$@ epub

upload-pt_BR-openrc: $(SSH_AGENT)
	cd $(HTMLDIROPENRC_pt_BR) ;\
	chmod g+w -R . ;\
	rsync --progress --recursive * $(USER)@www.linuxfromscratch.org:/srv/www/www.pt_BR.linuxfromscratch.org/view/lfs-svn/

upload-pt_BR-sysd: $(SSH_AGENT)
	cd $(HTMLDIRSYSD_pt_BR) ;\
	chmod g+w -R . ;\
	rsync --progress --recursive * $(USER)@www.linuxfromscratch.org:/srv/www/www.pt_BR.linuxfromscratch.org/view/lfs-systemd-svn/
HTMLDIROPENRC_zh_CN := html-zh_CN-openrc
HTMLDIRSYSD_zh_CN := html-zh_CN-systemd
HTMLTAROPENRC_zh_CN := LFS-OPENRC-BOOK-$(MILESTONE)-zh_CN-HTML.tar.bz2
HTMLTARSYSD_zh_CN := LFS-SYSD-BOOK-$(MILESTONE)-zh_CN-HTML.tar.bz2
PDFOPENRC_zh_CN := LFS-OPENRC-BOOK-$(MILESTONE)-zh_CN.pdf
PDFSYSD_zh_CN := LFS-SYSD-BOOK-$(MILESTONE)-zh_CN.pdf
EPUBOPENRC_zh_CN := LFS-OPENRC-BOOK-$(MILESTONE)-zh_CN.epub
EPUBSYSD_zh_CN := LFS-SYSD-BOOK-$(MILESTONE)-zh_CN.epub

XML_zh_CN := $(shell find $(ORIGDIR) -name '*.xml' -o -name '*stylesheets*' -prune -a -type f | sed "s|$(ORIGDIR)/|lfsgen-zh_CN/|g" | tr '\n' ' ')
PO_zh_CN := $(shell find $(ORIGDIR) -name '*.xml' -o -name '*stylesheets*' -prune -a -type f | sed "s|$(ORIGDIR)/|zh_CN/|g" | sed 's|.xml$$|.po|' | tr '\n' ' ')
PO += $(PO_zh_CN)
IMAGES_zh_CN := $(shell find images -type f | sed "s|^|lfsgen-zh_CN/|g" | tr '\n' ' ')
STYLESHEETS_zh_CN := $(shell find stylesheets -type f | sed "s|^|lfsgen-zh_CN/|g" | tr '\n' ' ')
COPY_zh_CN := $(addprefix lfsgen-zh_CN/,$(filestoget))

lfsgen-zh_CN/images/%: images/%
	mkdir -p $$(dirname $@)
	@rm -f $@
	cp $< $@

lfsgen-zh_CN/stylesheets/%: stylesheets/%
	mkdir -p $$(dirname $@)
	@rm -f $@
	cp $< $@

lfsgen-zh_CN/%.xml: $(ORIGDIR)/%.xml zh_CN/%.po sed-zh_CN
	mkdir -p $$(dirname $@)
	LANG=$(LANG_zh_CN) po4a-translate -k 0 -f docbook -m $< -l $@.tmp -p $(word 2,$^)
	./$(word 3,$^) $@
	rm $@.tmp

zh_CN/%.po: $(ORIGDIR)/%.xml
	mkdir -p $$(dirname $@)
	LANG=$(LANG_zh_CN) po4a-updatepo -f docbook -m $< -p $@
	python3 set-xml.py $@
	@touch $@

clean-gen-zh_CN:
	rm -rf lfsgen-zh_CN

clean-product-zh_CN:
	rm -rf $(HTMLTAROPENRC_zh_CN)
	rm -rf $(HTMLTARSYSD_zh_CN)
	rm -rf $(HTMLDIROPENRC_zh_CN)
	rm -rf $(HTMLDIRSYSD_zh_CN)
	rm -rf $(PDFOPENRC_zh_CN)
	rm -rf $(PDFSYSD_zh_CN)
	rm -rf $(EPUBOPENRC_zh_CN)
	rm -rf $(EPUBSYSD_zh_CN)

.SECONDEXPANSION:
$(addprefix lfsgen-zh_CN/,$(filestocopy)): INPUT=$(ORIGDIR)$(subst lfsgen-zh_CN,,$@)
$(addprefix lfsgen-zh_CN/,$(filestocopy)): $$(INPUT)
	mkdir -p $$(dirname $@)
	if [ -f $< ]; then cp $< $@; else cp -r $< $$(dirname $@); fi

genhtml-zh_CN-openrc: $(XML_zh_CN) $(COPY_zh_CN) $(IMAGES_zh_CN) $(STYLESHEETS_zh_CN)
	LANG=$(LANG_zh_CN) make -C lfsgen-zh_CN -j1 REV=openrc BASEDIR=../$(HTMLDIROPENRC_zh_CN) book

genhtml-zh_CN-sysd: $(XML_zh_CN) $(COPY_zh_CN) $(IMAGES_zh_CN) $(STYLESHEETS_zh_CN)
	LANG=$(LANG_zh_CN) make -C lfsgen-zh_CN -j1 REV=systemd BASEDIR=../$(HTMLDIRSYSD_zh_CN) book

genpdf-zh_CN-openrc: $(PDFOPENRC_zh_CN)

$(PDFOPENRC_zh_CN): $(XML_zh_CN) $(COPY_zh_CN) $(IMAGES_zh_CN) $(STYLESHEETS_zh_CN)
	LANG=$(LANG_zh_CN) make -C lfsgen-zh_CN -j1 REV=openrc BASEDIR=.. pdf
	mv LFS-OPENRC.pdf $@

genpdf-zh_CN-sysd: $(PDFSYSD_zh_CN)

$(PDFSYSD_zh_CN): $(XML_zh_CN) $(COPY_zh_CN) $(IMAGES_zh_CN) $(STYLESHEETS_zh_CN)
	LANG=$(LANG_zh_CN) make -C lfsgen-zh_CN -j1 REV=systemd BASEDIR=.. pdf
	mv LFS-SYSD-BOOK.pdf $@

gentar-zh_CN-openrc: $(HTMLTAROPENRC_zh_CN)
$(HTMLTAROPENRC_zh_CN): $(XML_zh_CN) $(COPY_zh_CN) $(IMAGES_zh_CN) $(STYLESHEETS_zh_CN) genhtml-zh_CN-openrc
	rm -f $@
	tar cjf $@ $(HTMLDIROPENRC_zh_CN)

gentar-zh_CN-sysd: $(HTMLTARSYSD_zh_CN)
$(HTMLTARSYSD_zh_CN): $(XML_zh_CN) $(COPY_zh_CN) $(IMAGES_zh_CN) $(STYLESHEETS_zh_CN) genhtml-zh_CN-sysd
	rm -f $@
	tar cjf $@ $(HTMLDIRSYSD_zh_CN)

genepub-zh_CN-openrc: $(EPUBOPENRC_zh_CN)
$(EPUBOPENRC_zh_CN): $(XML_zh_CN) $(COPY_zh_CN) $(IMAGES_zh_CN) $(STYLESHEETS_zh_CN)
	LANG=$(LANG_zh_CN) make -C lfsgen-zh_CN -j1 REV=openrc EPUB_OUTPUT=$@ epub

genepub-zh_CN-sysd: $(EPUBSYSD_zh_CN)
$(EPUBSYSD_zh_CN): $(XML_zh_CN) $(COPY_zh_CN) $(IMAGES_zh_CN) $(STYLESHEETS_zh_CN)
	LANG=$(LANG_zh_CN) make -C lfsgen-zh_CN -j1 REV=systemd EPUB_OUTPUT=$@ epub

upload-zh_CN-openrc: $(SSH_AGENT)
	cd $(HTMLDIROPENRC_zh_CN) ;\
	chmod g+w -R . ;\
	rsync --progress --recursive * $(USER)@www.linuxfromscratch.org:/srv/www/www.zh_CN.linuxfromscratch.org/view/lfs-svn/

upload-zh_CN-sysd: $(SSH_AGENT)
	cd $(HTMLDIRSYSD_zh_CN) ;\
	chmod g+w -R . ;\
	rsync --progress --recursive * $(USER)@www.linuxfromscratch.org:/srv/www/www.zh_CN.linuxfromscratch.org/view/lfs-systemd-svn/
